### ISSUE TITLE
Update problems

### ISSUE THREAD

**Issue by tropnikovvl** [devops-infra/docker-terragrunt#2233]
## :memo:  Brief description

The script you use to check new product versions has broken.
https://github.com/devops-infra/docker-terragrunt/actions/workflows/CRON.yml

## :warning: Checklist
* [x] Provided a clear and concise description of what the issue is.
* [ ] Given a clear and concise description of what is expected.
* [ ] Proposed a clear and concise description of any alternative solutions or other features.
* [x] Added any other context or screenshots about the feature request.
* [ ] Associated pull request has been already created and link was provided.

*Check [CONTRIBUTING.md][contributing] and [CODE_OF_CONDUCT.md][code] for more information*

[contributing]: https://github.com/devops-infra/.github/blob/master/CONTRIBUTING.md
[code]: https://github.com/devops-infra/.github/blob/master/CODE_OF_CONDUCT.md

**Comment by ChristophShyper** [comment]
Hello. Build is marked as failed there because there was nothing to update or there is pending update for TF/TG/OT. 
For the last few years updates to all dependencies were available every day so it was occurring very rarely. 
Maybe I'll update it so it doesn't fail since it's happening more now.
Thanks for being vigilant :)

**Comment by ChristophShyper** [comment]
Ok, looks like Google changed place where they specify SDK version https://github.com/devops-infra/docker-terragrunt/actions/runs/9738621730/job/26872493258#step:5:19
It happend few times already, they are very inconsistent.
